[phases.setup]
nixPkgs = ["python39", "python39Packages.pip", "python39Packages.setuptools"]

[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "echo 'Build phase completed'"
]

[start]
cmd = "python app.py"
